version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks: 
      - app-net

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - app-net
    depends_on:
      - backend

networks:
  app-net:
    driver: bridge