version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python app.py"

  redis:
    image: redis:alpine
