version: "3.8"

services:
  web:
    image: python:3.10
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python app.py"